{
 "title": "New dashboard Copy",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Resilience",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_verifyNewUser_successful\n\n"
    },
    {
     "expr": "resilience4j_circuitbreaker_verifyNewUser_state"
    },
    {
     "expr": "resilience4j_circuitbreaker_verifyNewUser_failed"
    }
   ]
  },
  {
   "title": "Gateway",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "gateway_requests_seconds_count" }
   ]
  },
  {
   "title": "Verify new user (manual)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "verifyNewUserManual_seconds_max"
    }
   ]
  }
 ]
}